Update opened.schema.json
Fix congruence with:

payload-schemas/api.github.com/common/issue.schema.json:65

"type": ["string", "null"] VS "type": "null"

error TS2339: Property 'title' does not exist on type 'never'.
  The intersection 'Issue & { state: "open"; closed_at: null; }' was reduced to 'never' because property 'closed_at' has conflicting types in some constituents.